// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="detect_and_recognize_detect_and_recognize,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.125300,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=7674,HLS_SYN_LUT=17720,HLS_VERSION=2024_2}" *)

module detect_and_recognize (
        ap_clk,
        ap_rst_n,
        frame_0_Addr_A,
        frame_0_EN_A,
        frame_0_WEN_A,
        frame_0_Din_A,
        frame_0_Dout_A,
        frame_0_Clk_A,
        frame_0_Rst_A,
        frame_1_Addr_A,
        frame_1_EN_A,
        frame_1_WEN_A,
        frame_1_Din_A,
        frame_1_Dout_A,
        frame_1_Clk_A,
        frame_1_Rst_A,
        frame_2_Addr_A,
        frame_2_EN_A,
        frame_2_WEN_A,
        frame_2_Din_A,
        frame_2_Dout_A,
        frame_2_Clk_A,
        frame_2_Rst_A,
        frame_3_Addr_A,
        frame_3_EN_A,
        frame_3_WEN_A,
        frame_3_Din_A,
        frame_3_Dout_A,
        frame_3_Clk_A,
        frame_3_Rst_A,
        frame_4_Addr_A,
        frame_4_EN_A,
        frame_4_WEN_A,
        frame_4_Din_A,
        frame_4_Dout_A,
        frame_4_Clk_A,
        frame_4_Rst_A,
        frame_5_Addr_A,
        frame_5_EN_A,
        frame_5_WEN_A,
        frame_5_Din_A,
        frame_5_Dout_A,
        frame_5_Clk_A,
        frame_5_Rst_A,
        frame_6_Addr_A,
        frame_6_EN_A,
        frame_6_WEN_A,
        frame_6_Din_A,
        frame_6_Dout_A,
        frame_6_Clk_A,
        frame_6_Rst_A,
        frame_7_Addr_A,
        frame_7_EN_A,
        frame_7_WEN_A,
        frame_7_Din_A,
        frame_7_Dout_A,
        frame_7_Clk_A,
        frame_7_Rst_A,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [31:0] frame_0_Addr_A;
output   frame_0_EN_A;
output  [0:0] frame_0_WEN_A;
output  [7:0] frame_0_Din_A;
input  [7:0] frame_0_Dout_A;
output   frame_0_Clk_A;
output   frame_0_Rst_A;
output  [31:0] frame_1_Addr_A;
output   frame_1_EN_A;
output  [0:0] frame_1_WEN_A;
output  [7:0] frame_1_Din_A;
input  [7:0] frame_1_Dout_A;
output   frame_1_Clk_A;
output   frame_1_Rst_A;
output  [31:0] frame_2_Addr_A;
output   frame_2_EN_A;
output  [0:0] frame_2_WEN_A;
output  [7:0] frame_2_Din_A;
input  [7:0] frame_2_Dout_A;
output   frame_2_Clk_A;
output   frame_2_Rst_A;
output  [31:0] frame_3_Addr_A;
output   frame_3_EN_A;
output  [0:0] frame_3_WEN_A;
output  [7:0] frame_3_Din_A;
input  [7:0] frame_3_Dout_A;
output   frame_3_Clk_A;
output   frame_3_Rst_A;
output  [31:0] frame_4_Addr_A;
output   frame_4_EN_A;
output  [0:0] frame_4_WEN_A;
output  [7:0] frame_4_Din_A;
input  [7:0] frame_4_Dout_A;
output   frame_4_Clk_A;
output   frame_4_Rst_A;
output  [31:0] frame_5_Addr_A;
output   frame_5_EN_A;
output  [0:0] frame_5_WEN_A;
output  [7:0] frame_5_Din_A;
input  [7:0] frame_5_Dout_A;
output   frame_5_Clk_A;
output   frame_5_Rst_A;
output  [31:0] frame_6_Addr_A;
output   frame_6_EN_A;
output  [0:0] frame_6_WEN_A;
output  [7:0] frame_6_Din_A;
input  [7:0] frame_6_Dout_A;
output   frame_6_Clk_A;
output   frame_6_Rst_A;
output  [31:0] frame_7_Addr_A;
output   frame_7_EN_A;
output  [0:0] frame_7_WEN_A;
output  [7:0] frame_7_Din_A;
input  [7:0] frame_7_Dout_A;
output   frame_7_Clk_A;
output   frame_7_Rst_A;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg[31:0] frame_0_Addr_A;
reg frame_0_EN_A;
reg[31:0] frame_1_Addr_A;
reg frame_1_EN_A;
reg[31:0] frame_2_Addr_A;
reg frame_2_EN_A;
reg[31:0] frame_3_Addr_A;
reg frame_3_EN_A;
reg[31:0] frame_4_Addr_A;
reg frame_4_EN_A;
reg[31:0] frame_5_Addr_A;
reg frame_5_EN_A;
reg[31:0] frame_6_Addr_A;
reg frame_6_EN_A;
reg[31:0] frame_7_Addr_A;
reg frame_7_EN_A;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [7:0] result;
reg    result_ap_vld;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_return;
reg   [0:0] targetBlock_reg_275;
wire    ap_CS_fsm_state3;
wire   [15:0] add_ln146_1_fu_198_p2;
reg   [15:0] add_ln146_1_reg_282;
wire    ap_CS_fsm_state4;
wire   [9:0] add_ln146_fu_203_p2;
reg   [9:0] add_ln146_reg_287;
wire   [0:0] icmp_ln146_fu_218_p2;
reg   [0:0] icmp_ln146_reg_296;
wire    ap_CS_fsm_state5;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_done;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_idle;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_ready;
wire   [31:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_Addr_A;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_EN_A;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_WEN_A;
wire   [7:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_Din_A;
wire   [31:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_Addr_A;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_EN_A;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_WEN_A;
wire   [7:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_Din_A;
wire   [31:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_Addr_A;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_EN_A;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_WEN_A;
wire   [7:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_Din_A;
wire   [31:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_Addr_A;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_EN_A;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_WEN_A;
wire   [7:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_Din_A;
wire   [31:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_Addr_A;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_EN_A;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_WEN_A;
wire   [7:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_Din_A;
wire   [31:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_Addr_A;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_EN_A;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_WEN_A;
wire   [7:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_Din_A;
wire   [31:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_Addr_A;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_EN_A;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_WEN_A;
wire   [7:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_Din_A;
wire   [31:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_Addr_A;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_EN_A;
wire   [0:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_WEN_A;
wire   [7:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_Din_A;
wire   [9:0] grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_x_out;
wire    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_x_out_ap_vld;
wire    grp_flood_fill_fu_144_ap_start;
wire    grp_flood_fill_fu_144_ap_done;
wire    grp_flood_fill_fu_144_ap_idle;
wire    grp_flood_fill_fu_144_ap_ready;
wire   [31:0] grp_flood_fill_fu_144_frame_0_Addr_A;
wire    grp_flood_fill_fu_144_frame_0_EN_A;
wire   [0:0] grp_flood_fill_fu_144_frame_0_WEN_A;
wire   [7:0] grp_flood_fill_fu_144_frame_0_Din_A;
wire   [31:0] grp_flood_fill_fu_144_frame_1_Addr_A;
wire    grp_flood_fill_fu_144_frame_1_EN_A;
wire   [0:0] grp_flood_fill_fu_144_frame_1_WEN_A;
wire   [7:0] grp_flood_fill_fu_144_frame_1_Din_A;
wire   [31:0] grp_flood_fill_fu_144_frame_2_Addr_A;
wire    grp_flood_fill_fu_144_frame_2_EN_A;
wire   [0:0] grp_flood_fill_fu_144_frame_2_WEN_A;
wire   [7:0] grp_flood_fill_fu_144_frame_2_Din_A;
wire   [31:0] grp_flood_fill_fu_144_frame_3_Addr_A;
wire    grp_flood_fill_fu_144_frame_3_EN_A;
wire   [0:0] grp_flood_fill_fu_144_frame_3_WEN_A;
wire   [7:0] grp_flood_fill_fu_144_frame_3_Din_A;
wire   [31:0] grp_flood_fill_fu_144_frame_4_Addr_A;
wire    grp_flood_fill_fu_144_frame_4_EN_A;
wire   [0:0] grp_flood_fill_fu_144_frame_4_WEN_A;
wire   [7:0] grp_flood_fill_fu_144_frame_4_Din_A;
wire   [31:0] grp_flood_fill_fu_144_frame_5_Addr_A;
wire    grp_flood_fill_fu_144_frame_5_EN_A;
wire   [0:0] grp_flood_fill_fu_144_frame_5_WEN_A;
wire   [7:0] grp_flood_fill_fu_144_frame_5_Din_A;
wire   [31:0] grp_flood_fill_fu_144_frame_6_Addr_A;
wire    grp_flood_fill_fu_144_frame_6_EN_A;
wire   [0:0] grp_flood_fill_fu_144_frame_6_WEN_A;
wire   [7:0] grp_flood_fill_fu_144_frame_6_Din_A;
wire   [31:0] grp_flood_fill_fu_144_frame_7_Addr_A;
wire    grp_flood_fill_fu_144_frame_7_EN_A;
wire   [0:0] grp_flood_fill_fu_144_frame_7_WEN_A;
wire   [7:0] grp_flood_fill_fu_144_frame_7_Din_A;
wire   [31:0] grp_flood_fill_fu_144_ap_return;
wire    grp_recognize_character_fu_166_ap_start;
wire    grp_recognize_character_fu_166_ap_done;
wire    grp_recognize_character_fu_166_ap_idle;
wire    grp_recognize_character_fu_166_ap_ready;
wire   [6:0] grp_recognize_character_fu_166_ap_return;
reg   [0:0] cleanup_dest_slot_0_i_reg_109;
reg    ap_block_state5_on_subcall_done;
reg    grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [9:0] x_loc_fu_98;
reg    grp_flood_fill_fu_144_ap_start_reg;
reg    grp_recognize_character_fu_166_ap_start_reg;
wire    ap_CS_fsm_state6;
wire   [0:0] or_cond_i_fu_231_p2;
wire    ap_CS_fsm_state7;
reg   [15:0] phi_mul3_fu_86;
reg   [9:0] y_fu_90;
reg   [31:0] blob_prefix_sum_0_fu_94;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start_reg = 1'b0;
#0 grp_flood_fill_fu_144_ap_start_reg = 1'b0;
#0 grp_recognize_character_fu_166_ap_start_reg = 1'b0;
#0 phi_mul3_fu_86 = 16'd0;
#0 y_fu_90 = 10'd0;
#0 blob_prefix_sum_0_fu_94 = 32'd0;
end

detect_and_recognize_detect_and_recognize_Pipeline_VITIS_LOOP_147_2 grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start),
    .ap_done(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_done),
    .ap_idle(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_idle),
    .ap_ready(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_ready),
    .phi_mul3(phi_mul3_fu_86),
    .frame_0_Addr_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_Addr_A),
    .frame_0_EN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_EN_A),
    .frame_0_WEN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_WEN_A),
    .frame_0_Din_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_Din_A),
    .frame_0_Dout_A(frame_0_Dout_A),
    .frame_1_Addr_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_Addr_A),
    .frame_1_EN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_EN_A),
    .frame_1_WEN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_WEN_A),
    .frame_1_Din_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_Din_A),
    .frame_1_Dout_A(frame_1_Dout_A),
    .frame_2_Addr_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_Addr_A),
    .frame_2_EN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_EN_A),
    .frame_2_WEN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_WEN_A),
    .frame_2_Din_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_Din_A),
    .frame_2_Dout_A(frame_2_Dout_A),
    .frame_3_Addr_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_Addr_A),
    .frame_3_EN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_EN_A),
    .frame_3_WEN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_WEN_A),
    .frame_3_Din_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_Din_A),
    .frame_3_Dout_A(frame_3_Dout_A),
    .frame_4_Addr_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_Addr_A),
    .frame_4_EN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_EN_A),
    .frame_4_WEN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_WEN_A),
    .frame_4_Din_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_Din_A),
    .frame_4_Dout_A(frame_4_Dout_A),
    .frame_5_Addr_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_Addr_A),
    .frame_5_EN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_EN_A),
    .frame_5_WEN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_WEN_A),
    .frame_5_Din_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_Din_A),
    .frame_5_Dout_A(frame_5_Dout_A),
    .frame_6_Addr_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_Addr_A),
    .frame_6_EN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_EN_A),
    .frame_6_WEN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_WEN_A),
    .frame_6_Din_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_Din_A),
    .frame_6_Dout_A(frame_6_Dout_A),
    .frame_7_Addr_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_Addr_A),
    .frame_7_EN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_EN_A),
    .frame_7_WEN_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_WEN_A),
    .frame_7_Din_A(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_Din_A),
    .frame_7_Dout_A(frame_7_Dout_A),
    .x_out(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_x_out),
    .x_out_ap_vld(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_x_out_ap_vld),
    .ap_return(grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_return)
);

detect_and_recognize_flood_fill grp_flood_fill_fu_144(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_flood_fill_fu_144_ap_start),
    .ap_done(grp_flood_fill_fu_144_ap_done),
    .ap_idle(grp_flood_fill_fu_144_ap_idle),
    .ap_ready(grp_flood_fill_fu_144_ap_ready),
    .frame_0_Addr_A(grp_flood_fill_fu_144_frame_0_Addr_A),
    .frame_0_EN_A(grp_flood_fill_fu_144_frame_0_EN_A),
    .frame_0_WEN_A(grp_flood_fill_fu_144_frame_0_WEN_A),
    .frame_0_Din_A(grp_flood_fill_fu_144_frame_0_Din_A),
    .frame_0_Dout_A(frame_0_Dout_A),
    .frame_1_Addr_A(grp_flood_fill_fu_144_frame_1_Addr_A),
    .frame_1_EN_A(grp_flood_fill_fu_144_frame_1_EN_A),
    .frame_1_WEN_A(grp_flood_fill_fu_144_frame_1_WEN_A),
    .frame_1_Din_A(grp_flood_fill_fu_144_frame_1_Din_A),
    .frame_1_Dout_A(frame_1_Dout_A),
    .frame_2_Addr_A(grp_flood_fill_fu_144_frame_2_Addr_A),
    .frame_2_EN_A(grp_flood_fill_fu_144_frame_2_EN_A),
    .frame_2_WEN_A(grp_flood_fill_fu_144_frame_2_WEN_A),
    .frame_2_Din_A(grp_flood_fill_fu_144_frame_2_Din_A),
    .frame_2_Dout_A(frame_2_Dout_A),
    .frame_3_Addr_A(grp_flood_fill_fu_144_frame_3_Addr_A),
    .frame_3_EN_A(grp_flood_fill_fu_144_frame_3_EN_A),
    .frame_3_WEN_A(grp_flood_fill_fu_144_frame_3_WEN_A),
    .frame_3_Din_A(grp_flood_fill_fu_144_frame_3_Din_A),
    .frame_3_Dout_A(frame_3_Dout_A),
    .frame_4_Addr_A(grp_flood_fill_fu_144_frame_4_Addr_A),
    .frame_4_EN_A(grp_flood_fill_fu_144_frame_4_EN_A),
    .frame_4_WEN_A(grp_flood_fill_fu_144_frame_4_WEN_A),
    .frame_4_Din_A(grp_flood_fill_fu_144_frame_4_Din_A),
    .frame_4_Dout_A(frame_4_Dout_A),
    .frame_5_Addr_A(grp_flood_fill_fu_144_frame_5_Addr_A),
    .frame_5_EN_A(grp_flood_fill_fu_144_frame_5_EN_A),
    .frame_5_WEN_A(grp_flood_fill_fu_144_frame_5_WEN_A),
    .frame_5_Din_A(grp_flood_fill_fu_144_frame_5_Din_A),
    .frame_5_Dout_A(frame_5_Dout_A),
    .frame_6_Addr_A(grp_flood_fill_fu_144_frame_6_Addr_A),
    .frame_6_EN_A(grp_flood_fill_fu_144_frame_6_EN_A),
    .frame_6_WEN_A(grp_flood_fill_fu_144_frame_6_WEN_A),
    .frame_6_Din_A(grp_flood_fill_fu_144_frame_6_Din_A),
    .frame_6_Dout_A(frame_6_Dout_A),
    .frame_7_Addr_A(grp_flood_fill_fu_144_frame_7_Addr_A),
    .frame_7_EN_A(grp_flood_fill_fu_144_frame_7_EN_A),
    .frame_7_WEN_A(grp_flood_fill_fu_144_frame_7_WEN_A),
    .frame_7_Din_A(grp_flood_fill_fu_144_frame_7_Din_A),
    .frame_7_Dout_A(frame_7_Dout_A),
    .start_x(x_loc_fu_98),
    .start_y(y_fu_90),
    .ap_return(grp_flood_fill_fu_144_ap_return)
);

detect_and_recognize_recognize_character grp_recognize_character_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_recognize_character_fu_166_ap_start),
    .ap_done(grp_recognize_character_fu_166_ap_done),
    .ap_idle(grp_recognize_character_fu_166_ap_idle),
    .ap_ready(grp_recognize_character_fu_166_ap_ready),
    .blob_prefix_sum_val(blob_prefix_sum_0_fu_94),
    .ap_return(grp_recognize_character_fu_166_ap_return)
);

detect_and_recognize_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .result(result),
    .result_ap_vld(result_ap_vld),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_ready == 1'b1)) begin
            grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_flood_fill_fu_144_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state4) & (targetBlock_reg_275 == 1'd0))) begin
            grp_flood_fill_fu_144_ap_start_reg <= 1'b1;
        end else if ((grp_flood_fill_fu_144_ap_ready == 1'b1)) begin
            grp_flood_fill_fu_144_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_recognize_character_fu_166_ap_start_reg <= 1'b0;
    end else begin
        if (((or_cond_i_fu_231_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
            grp_recognize_character_fu_166_ap_start_reg <= 1'b1;
        end else if ((grp_recognize_character_fu_166_ap_ready == 1'b1)) begin
            grp_recognize_character_fu_166_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        blob_prefix_sum_0_fu_94 <= 32'd0;
    end else if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        blob_prefix_sum_0_fu_94 <= grp_flood_fill_fu_144_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (targetBlock_reg_275 == 1'd1))) begin
        cleanup_dest_slot_0_i_reg_109 <= 1'd1;
    end else if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        cleanup_dest_slot_0_i_reg_109 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_mul3_fu_86 <= 16'd0;
    end else if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
        phi_mul3_fu_86 <= add_ln146_1_reg_282;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        y_fu_90 <= 10'd0;
    end else if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
        y_fu_90 <= add_ln146_reg_287;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln146_1_reg_282 <= add_ln146_1_fu_198_p2;
        add_ln146_reg_287 <= add_ln146_fu_203_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln146_reg_296 <= icmp_ln146_fu_218_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        targetBlock_reg_275 <= grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_x_out_ap_vld == 1'b1))) begin
        x_loc_fu_98 <= grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_x_out;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state5_on_subcall_done)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_recognize_character_fu_166_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_recognize_character_fu_166_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_recognize_character_fu_166_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_0_Addr_A = grp_flood_fill_fu_144_frame_0_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_0_Addr_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_Addr_A;
    end else begin
        frame_0_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_0_EN_A = grp_flood_fill_fu_144_frame_0_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_0_EN_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_0_EN_A;
    end else begin
        frame_0_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_1_Addr_A = grp_flood_fill_fu_144_frame_1_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_1_Addr_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_Addr_A;
    end else begin
        frame_1_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_1_EN_A = grp_flood_fill_fu_144_frame_1_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_1_EN_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_1_EN_A;
    end else begin
        frame_1_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_2_Addr_A = grp_flood_fill_fu_144_frame_2_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_2_Addr_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_Addr_A;
    end else begin
        frame_2_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_2_EN_A = grp_flood_fill_fu_144_frame_2_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_2_EN_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_2_EN_A;
    end else begin
        frame_2_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_3_Addr_A = grp_flood_fill_fu_144_frame_3_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_3_Addr_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_Addr_A;
    end else begin
        frame_3_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_3_EN_A = grp_flood_fill_fu_144_frame_3_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_3_EN_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_3_EN_A;
    end else begin
        frame_3_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_4_Addr_A = grp_flood_fill_fu_144_frame_4_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_4_Addr_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_Addr_A;
    end else begin
        frame_4_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_4_EN_A = grp_flood_fill_fu_144_frame_4_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_4_EN_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_4_EN_A;
    end else begin
        frame_4_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_5_Addr_A = grp_flood_fill_fu_144_frame_5_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_5_Addr_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_Addr_A;
    end else begin
        frame_5_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_5_EN_A = grp_flood_fill_fu_144_frame_5_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_5_EN_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_5_EN_A;
    end else begin
        frame_5_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_6_Addr_A = grp_flood_fill_fu_144_frame_6_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_6_Addr_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_Addr_A;
    end else begin
        frame_6_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_6_EN_A = grp_flood_fill_fu_144_frame_6_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_6_EN_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_6_EN_A;
    end else begin
        frame_6_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_7_Addr_A = grp_flood_fill_fu_144_frame_7_Addr_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_7_Addr_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_Addr_A;
    end else begin
        frame_7_Addr_A = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (targetBlock_reg_275 == 1'd0))) begin
        frame_7_EN_A = grp_flood_fill_fu_144_frame_7_EN_A;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        frame_7_EN_A = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_frame_7_EN_A;
    end else begin
        frame_7_EN_A = 1'b0;
    end
end

always @ (*) begin
    if (((grp_recognize_character_fu_166_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        result_ap_vld = 1'b1;
    end else begin
        result_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b0 == ap_block_state5_on_subcall_done) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((or_cond_i_fu_231_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((grp_recognize_character_fu_166_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln146_1_fu_198_p2 = (phi_mul3_fu_86 + 16'd100);

assign add_ln146_fu_203_p2 = (y_fu_90 + 10'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state5_on_subcall_done = ((grp_flood_fill_fu_144_ap_done == 1'b0) & (targetBlock_reg_275 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign frame_0_Clk_A = ap_clk;

assign frame_0_Din_A = 8'd0;

assign frame_0_Rst_A = ap_rst_n_inv;

assign frame_0_WEN_A = 1'd0;

assign frame_1_Clk_A = ap_clk;

assign frame_1_Din_A = 8'd0;

assign frame_1_Rst_A = ap_rst_n_inv;

assign frame_1_WEN_A = 1'd0;

assign frame_2_Clk_A = ap_clk;

assign frame_2_Din_A = 8'd0;

assign frame_2_Rst_A = ap_rst_n_inv;

assign frame_2_WEN_A = 1'd0;

assign frame_3_Clk_A = ap_clk;

assign frame_3_Din_A = 8'd0;

assign frame_3_Rst_A = ap_rst_n_inv;

assign frame_3_WEN_A = 1'd0;

assign frame_4_Clk_A = ap_clk;

assign frame_4_Din_A = 8'd0;

assign frame_4_Rst_A = ap_rst_n_inv;

assign frame_4_WEN_A = 1'd0;

assign frame_5_Clk_A = ap_clk;

assign frame_5_Din_A = 8'd0;

assign frame_5_Rst_A = ap_rst_n_inv;

assign frame_5_WEN_A = 1'd0;

assign frame_6_Clk_A = ap_clk;

assign frame_6_Din_A = 8'd0;

assign frame_6_Rst_A = ap_rst_n_inv;

assign frame_6_WEN_A = 1'd0;

assign frame_7_Clk_A = ap_clk;

assign frame_7_Din_A = 8'd0;

assign frame_7_Rst_A = ap_rst_n_inv;

assign frame_7_WEN_A = 1'd0;

assign grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start = grp_detect_and_recognize_Pipeline_VITIS_LOOP_147_2_fu_122_ap_start_reg;

assign grp_flood_fill_fu_144_ap_start = grp_flood_fill_fu_144_ap_start_reg;

assign grp_recognize_character_fu_166_ap_start = grp_recognize_character_fu_166_ap_start_reg;

assign icmp_ln146_fu_218_p2 = ((add_ln146_reg_287 < 10'd600) ? 1'b1 : 1'b0);

assign or_cond_i_fu_231_p2 = (icmp_ln146_reg_296 & cleanup_dest_slot_0_i_reg_109);

assign result = grp_recognize_character_fu_166_ap_return;

endmodule //detect_and_recognize
